### ISSUE TITLE
Много нулей + точка и десятичное получается хрень

### ISSUE THREAD

**Issue by dustwind** [dustwind/qt_calc#3]
Если жать много нулей, потом ставить точку и вводить число, то программа перестает реагировать

**Comment by DrBallMD** [comment]
не удалось воспроизвести
![060316_083224](https://cloud.githubusercontent.com/assets/8522321/15780425/ca6c4164-29cb-11e6-93ec-423d6dfd167b.jpg)

**Comment by dustwind** [comment]
версия последняя была?

**Comment by dustwind** [comment]
хм, и правда норм все. странно
